spring:
  application:
    name: test

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.20:3306/lottery?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  typeAliasesPackage: cn.joral.demo.pojo.User
